language: python

git:
  submodules: false

python:
  - "2.7"
  - "3.4"
  - "pypy"

env:
  - FLASK_VERSION="==0.9"
  - FLASK_VERSION="==0.10"
  - FLASK_VERSION="" # Current.

before_install:
  - sudo apt-get install libjpeg8 libjpeg8-dev libfreetype6 libfreetype6-dev zlib1g-dev tree
  - sudo ln -s /usr/lib/`uname -i`-linux-gnu/libjpeg.so.8 ~/virtualenv/python2.7/lib/
  - sudo ln -s /usr/lib/`uname -i`-linux-gnu/libfreetype.so ~/virtualenv/python2.7/lib/
  - sudo ln -s /usr/lib/`uname -i`-linux-gnu/libz.so ~/virtualenv/python2.7/lib/
  - pip install Pillow==3.1.2
  - pip install six>=1.10.0
  - pip install itsdangerous>=0.24
  - pip install nose
  - pip install codecov

install:
  - pip install Flask$FLASK_VERSION
  - pip install -e .

script: nosetests --with-coverage --cover-package=flask_imagine

after_success:
  - codecov
